name: bloc_chain
description: Global event dispatching for `bloc`.
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/SEGVeenstra/bloc_chain

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  bloc: ^8.0.2
